version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_financial
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: FinancialControl
    ports:
      - "5433:5432"   # acessar do host via localhost:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

  financialcontrol:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: financialcontrol
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
