version: "3.9"

services:
  financialcontrol:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: financialcontrol
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./FinancialControl:/src # Permite alterações locais refletirem no container (dev)
    environment:
      ASPNETCORE_URLS: http://+:8080
    restart: unless-stopped
