version: "3.9"

services:
  financialcontrol:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ConnectionPostgres: Host=postgres;Port=5432;Database=FinancialControl;Username=postgres;Password=1234
